import "@/app/styles/globals.css";
// import Header from '@/app/component/Header'
// import Footer from '@/app/component/Footer'

// import { Provider } from 'react-redux';
// import { wrapper }  from '@/store';
// import { useMemo } from 'react';
// import { ReduxProvider } from "@/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const store = useMemo(() => makeStore(), []);
  return (
    // <html lang="zh">
    //   <body>
    <>
      {children}
    </>
    //   </body>
    // </html>
  );
}
