import localFont from "next/font/local";
import "./globals.css";
import Header from './component/Header'
// import { Provider } from 'react-redux';
// import makeStore from '@/store';
// import { useMemo } from 'react';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const store = useMemo(() => makeStore(), []);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Provider store={store}> */}
          <Header></Header>
          {children}
          <footer >Footer</footer>
        {/* </Provider> */}
      </body>
    </html>
  );
}
